# Generated by Django 4.2.19 on 2025-02-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
