# Generated by Django 4.2.19 on 2025-02-14 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_alter_child_slug'),
        ('bookings', '0002_alter_booking_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='children.child'),
        ),
    ]
