# Generated by Django 4.2.19 on 2025-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=10),
        ),
    ]
